// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjf6S3GsJe5_5b2m4y1EdgBTDCtRaG54',
    appId: '1:703943868731:web:a78214da977da6e865f71e',
    messagingSenderId: '703943868731',
    projectId: 'smart-ix-task',
    authDomain: 'smart-ix-task.firebaseapp.com',
    storageBucket: 'smart-ix-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHqa2nf4nXQYpA5z2k5L_OvBptI2uKCs',
    appId: '1:703943868731:android:2211ecd6957527e965f71e',
    messagingSenderId: '703943868731',
    projectId: 'smart-ix-task',
    storageBucket: 'smart-ix-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv_R2I9u7XB-pvSmaMK_TUCqthodDw1qQ',
    appId: '1:703943868731:ios:ed3d435ba7dd63e365f71e',
    messagingSenderId: '703943868731',
    projectId: 'smart-ix-task',
    storageBucket: 'smart-ix-task.appspot.com',
    iosClientId: '703943868731-7malg5mbi4k0hta5quvidgv493pgp0cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartIxTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv_R2I9u7XB-pvSmaMK_TUCqthodDw1qQ',
    appId: '1:703943868731:ios:ed3d435ba7dd63e365f71e',
    messagingSenderId: '703943868731',
    projectId: 'smart-ix-task',
    storageBucket: 'smart-ix-task.appspot.com',
    iosClientId: '703943868731-7malg5mbi4k0hta5quvidgv493pgp0cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartIxTask',
  );
}
